SET SERVEROUTPUT ON;

DECLARE
  V_NUM NUMBER := &ENTER_A_NUMBER;

BEGIN
  IF MOD(V_NUM,2)=0 THEN 
    DBMS_OUTPUT.PUT_LINE(V_NUM||' Is EVEN');
  ELSE
    DBMS_OUTPUT.PUT_LINE(V_NUM||' Is ODD');
  END IF;
    DBMS_OUTPUT.PUT_LINE('IF THEN ELSE DONE');
END ;