select * from event_recurring_5114

select * from event_recurring_5113


/*DUE TO PROBLEM WITH OCS WE NEED TO SELF POPULATE OUR TABLE
HENCE WE GO AHEAD AND UPDATE THE ROWS.
SO FIRST WE NEED TO INSERT 5113 INTO 5114

QUERY IS BELOW */

/*QUERY 1*/
INSERT INTO event_recurring_5114
SELECT * FROM event_recurring_5113;


/*NOW WE DO OUR UPDATES*/
SELECT * FROM event_recurring_5114

/*WE UPDATE BILLING_CYCLE_ID FIRST*/

SELECT * FROM  event_recurring_5114 WHERE TRUNC(CREATED_DATE)='01-JUL-21'

--UPDATE event_recurring_5114 SET BILLING_CYCLE_ID=5114 WHERE BILLING_CYCLE_ID=5113;

/*NOW WE HAVE TO UPDATE THE DATES PLEASE BE CAREFUL SOME OF THEM YOU HAVE TO DO TRUNC AND TO CHAR THING */
--UPDATE event_recurring_5114 SET EVENT_BEGIN_TIME='01-JUL-21' WHERE EVENT_BEGIN_TIME='01-JUN-21'

--UPDATE event_recurring_5114 SET EVENT_END_TIME='01-AUG-21' WHERE EVENT_END_TIME='01-JUL-21'

--UPDATE event_recurring_5114 SET BAL_UPDATE_DATE=TRUNC(SYSDATE-3) WHERE TRUNC(BAL_UPDATE_DATE)='01-JUL-21'

--UPDATE event_recurring_5114 SET STATE_DATE=TRUNC(SYSDATE-3) WHERE TRUNC(STATE_DATE)='01-JUL-21'

--UPDATE event_recurring_5114 SET CREATED_DATE=TRUNC(SYSDATE-3) WHERE TRUNC(CREATED_DATE)='01-JUL-21'
