SELECT A.*,B.CUST_NAME FROM
(SELECT A.ACC_NBR,B.SUBS_ID,B.CUST_ID FROM 
(SELECT MAX(SUBS_ID) SUBS_ID,ACC_NBR FROM SUBS
HAVING COUNT(*)>1
GROUP BY ACC_NBR) A,(SELECT * FROM SUBS)B
WHERE A.SUBS_ID=B.SUBS_ID) A,CUST B,PROD C
WHERE A.CUST_ID=B.CUST_ID
AND A.SUBS_ID=C.PROD_ID
AND C.PROD_STATE IN ('G','A')
